### ISSUE TITLE
运行不起来缺少文件

### ISSUE THREAD

**Issue by hajiuxbz** [zluckymn/HanlpNet#1]
net下有了ml.net据说可以无缝使用python的模型 能否了解下

**Comment by zluckymn** [comment]
Package\java\hanlp\IKVM.OpenJDK.Core.dll
Package\java\hanlp\IKVM.OpenJDK.Text.dll
Package\java\hanlp\IKVM.OpenJDK.Util.dll
Package\java\hanlp\IKVM.Runtime.dll
提示缺少的dll 从以上路径载入一下
![image](https://user-images.githubusercontent.com/5327219/179470487-14c9382e-6d1f-4606-9e8d-69444e53899d.png)
